### ISSUE TITLE
Enhacements on Waypoints

### ISSUE THREAD

**Issue by peixespnsc** [peixespnsc/speciesDatabase#21]
- Delete from "db_install.sql" the "camp_waypoints", and from "db_update.sql" the lines that you already copy to "wpt_install"
- Delete from "wpt_install" all "DROP TABLE IF EXISTS ..." commands
- Change "camp_units" and "camp_units_types" respectilly to "wpt_units" and "wpt_units_types"
- Do not change the table "camp_waypoints" to "wpt_waypoints" in the creation of the table. Keep the table with "camp_waypoints" name, and then create a SQL command "ALTER TABLE ..."
- Also, all "ALTER TABLE ..." are with "wpt_waypoint" name. So, the command to alter table's name have to come first
- Change files' names on admin: "camp_waypoints", "camp_units", "camp_units_types", respectilly to "wpt_waypoints", "wpt_units", "wpt_units_types"
- Change PHP file "libriries/campaigns/waypoints.php" to a proper folder
- Change all PHP files that uses those tables that we have change their names. A complete list must be provide. Let's contribute on this

**Comment by peixespnsc** [comment]
campaign.php
tomb.php
tombs_card.php
tombs_table.php
waypoint.php
waypoints_card.php
admin/camp_tomb.php
admin/camp_unit.php
admin/camp_unit_type.php
admin/camp_units.php
admin/camp_units_types.php
admin/camp_waypoint.php
admin/camp_waypoints.php
libraries/campaings/campaigns.php
libraries/campaings/waypoints.php

**Comment by TNMedeiros** [comment]
Okay, I will work on it. Thanks!

**Comment by TNMedeiros** [comment]
The requested changes have been made. Please, verify the pull request. 
**In addition:** I copied PHP file "**libraries/campaigns/waypoints.php**" to a proper folder on "**libraries/waypoints/waypoints.php**" , but the original file didn't delete, so I just erased the script.

**Comment by peixespnsc** [comment]
I also can't delete this... but I'm closing anyway

**Comment by peixespnsc** [comment]
You need to rename these files
- admin/camp_unit.php
- admin/camp_unit_type.php
- admin/camp_waypoint.php

**Comment by TNMedeiros** [comment]
The requested changes have been made. It seems the SQL in "tombs_table.php" file doesn't need any correction.
