### ISSUE TITLE
Correct db table "camp_campaigns"

### ISSUE THREAD

**Issue by peixespnsc** [peixespnsc/speciesDatabase#8]
Correct db table "camp_campaigns" thats'is mispeeling (camp_campaings).
After, correct in PHP files the SQLs

- campaign.php
- campaigns_card.php
- tomb.php
- tombs_card.php
- tombs_table.php
- admin/camp_campaing.php
- admin/camp_campaings.php
- libraries/campaigns/campaigns.php

**Comment by peixespnsc** [comment]
Please include the SQL line in includes/db/db_update.sql, with your comments

**Comment by TNMedeiros** [comment]
The corrections have been done.

**Comment by peixespnsc** [comment]
The first two files still are missing.
Please, correct them so I can commit everything once.

**Comment by felipeabranches** [comment]
Sorry, my mistake, these files are with the SQL form the librareis
