### ISSUE TITLE
Create db table "wpt_countries"

### ISSUE THREAD

**Issue by peixespnsc** [peixespnsc/speciesDatabase#9]
Use this project https://gist.github.com/adhipg/1600028
Add the fields

- description
- note
- image
- published

**Comment by peixespnsc** [comment]
Create a file on includes/db/wpt_country_install.sql, only with the statement to create the table, not to insert rows

**Comment by peixespnsc** [comment]
You already created the file, thanks!

**Comment by peixespnsc** [comment]
Please, make the amends to the table's name to plural

**Comment by TNMedeiros** [comment]
The table's name was set to plural.

**Comment by peixespnsc** [comment]
Please chanfe the file's name to plural too.

**Comment by peixespnsc** [comment]
You already changed, sorry.
